language: ruby
rvm:
- 2.5.0
before_script:
- npm install -g bower
- bower install
- chmod +x ./script/deploy.sh
script: bash ./script/deploy.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: AyushG3112@gmail.com
  - ENCRYPTION_LABEL: 6766cef25353
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_6766cef25353_key -iv $encrypted_6766cef25353_iv
  -in travis_ayushg3112_blog.enc -out travis_ayushg3112_blog -d
